### PR TITLE
Added 20180619 Machine Learning

### PR DESCRIPTION
**Pull request by minh2182000**

### CODE REVIEW

**Comment by gadenbuie** [comment]
Thanks @minh2182000, looking forward to the talk!

Would it be possible for you to trim the PR a bit down to just the source files and the rendered `.md` and/or `.html` files without the copy of mathjax? 

If you don’t have time I can do it tonight or early tomorrow.

**Comment by minh2182000** [comment]
I need mathjax for an equation in the html file but that equation isn't important. We don't have issue with space, do we?

**Comment by tgerke** [comment]
Agree, really looking forward to this tomorrow!

Re: mathjax. Perhaps not an issue with space, as much as a a desire for a tidier repository, particularly for attendees who might not be as familiar with github and/or the reasons behind needing the full copy to make the .md render. If the equation is truly non-critical (or you would like to load rendered versions as suggested), I think the repo would be much more accessible without the mathjax files and, importantly, would appropriately draw more attention to the cool R stuff you’re showing in the actual talk!

**Comment by gadenbuie** [comment]
Thank you for clarifying @tgerke that was my thinking exactly. I think it’d be fine to link to a stable online version of mathjax as long as the source files are included.

**Comment by minh2182000** [comment]
I cleaned it up

**Comment by gadenbuie** [comment]
This is great, thanks @minh2182000! I’ll merge this when I get into the office. 

BTW, are you on Twitter? If so, send me your user name and I’ll include you when I tweet about the talk from the UseRsTampa account.

**Comment by minh2182000** [comment]
Thank you! i don't use Twitter.

**Pull request merged**
